// Code goes here

$(function() {
    var availableMasterCourses = [
      "Bachelor of Architecture",
			"Bachelor of Biomedical Science",
			"Bachelor of Business Administration",
			"Bachelor of Clinical Science",
			"Bachelor of Commerce",
			"Bachelor of Computer Information Systems",
			"BSc Construction Technology",
			"Bachelor of Criminal Justice",
			"Bachelor of Divinity",
			"Bachelor of Economics",
			"Bachelor of Education",
			"Bachelor of Engineering",
			"Bachelor of Fine Arts",
			"Bachelor of Information Systems",
			"Bachelor of Management",
			"Bachelor of Music",
			"Bachelor of Pharmacy",
			"Bachelor of Philosophy",
			"Bachelor of Social Work",
			"Bachelor of Accountancy",
			"Bachelor of Arts in American Studies",
			"Bachelor of Arts in American Indian Studies",
			"Bachelor of Arts in Applied Psychology",
			"Bachelor of Arts in Biology",
			"Bachelor of Arts in Anthropology",
			"Bachelor of Arts in Child Advocacy",
			"Bachelor of Arts in Clinical Psychology",
			"Bachelor of Arts in Forensic Psychology",
			"Bachelor of Arts in Organizational Psychology",
			"BSc Aerospace Engineering",
			"BSc Actuarial",
			"BSc Agriculture",
			"BSc Architecture",
			"BSc Architectural Engineering",
			"BSc Biology",
			"BSc Biomedical Engineering",
			"BSc Business Administration",
			"BSc Chemical Engineering",
			"BSc Chemistry",
			"BSc Civil Engineering",
			"BSc Clinical Laboratory Science",
			"BSc Cognitive Science",
			"BSc Computer Engineering",
			"BSc Computer Science",
			"BSc Construction Engineering",
			"BSc Construction Management",
			"BSc Criminal Justice",
			"BSc Criminology",
			"BSc Diagnostic Radiography",
			"BSc Education",
			"BSc Electrical Engineering",
			"BSc Engineering Physics",
			"BSc Engineering Science",
			"BSc Engineering Technology",
			"BSc English Literature",
			"BSc Environmental Engineering",
			"BSc Environmental Science",
			"BSc Environmental Studies",
			"BSc Food Science",
			"BSc Foreign Service",
			"BSc Forensic Science",
			"BSc Forestry",
			"BSc History",
			"BSc Hospitality Management",
			"BSc Human Resources Management",
			"BSc Industrial Engineering",
			"BSc Information Technology",
			"BSc Information Systems",
			"BSc Integrated Science, Business and Technology",
			"BSc International Relations",
			"BSc Journalism",
			"BSc Management",
			"BSc Manufacturing Engineering",
			"BSc Marketing",
			"BSc Mathematics",
			"BSc Mechanical Engineering",
			"BSc Medical Technology",
			"BSc Meteorology",
			"BSc Microbiology",
			"BSc Mining Engineering",
			"BSc Molecular Biology",
			"BSc Neuroscience",
			"BSc Nursing",
			"BSc Nutrition science",
			"BSc Software Engineering",
			"BSc Petroleum Engineering",
			"BSc Podiatry",
			"BSc Pharmacology",
			"BSc Pharmacy",
			"BSc Physical Therapy",
			"BSc Physics",
			"BSc Plant Science",
			"BSc Politics",
			"BSc Psychology",
			"BSc Quantity Surveying Engineering",
			"BSc Radiologic Technology",
			"BSc Real-Time Interactive Simulation",
			"BSc Religion",
			"BSc Respiratory Therapy",
			"BSc Risk Management and Insurance",
			"BSc Science Education",
			"BSc Systems Engineering",
			"Bachelor of Music in Jazz Studies",
			"Bachelor of Music in Composition",
			"Bachelor of Music in Performance",
			"Bachelor of Music in Theory",
			"Bachelor of Music in Music Education",
			"Bachelor of Sports Management",
			"Master by Research",
			"Master of Accountancy",
			"Master of Advanced Study",
			"Master of Applied Mathematical Sciences",
			"Master of Applied Science",
			"Master of Architecture",
			"MA Liberal Studies",
			"MA Strategic Communication Management",
			"MA Teaching",
			"Master of Bioinformatics",
			"Master of Business Administration",
			"Master of Business",
			"Master of Business Economics",
			"Master of Business Engineering",
			"Master of Business Informatics",
			"Master of Chemistry",
			"Master of City Planning",
			"Master of Commerce",
			"Master of Computational Finance",
			"Master of Computer Applications",
			"Master of Computer Science",
			"Master of Communication",
			"Master of Counselling",
			"Master of Criminal Justice",
			"Master in Creative Technologies",
			"Master of Design",
			"Master of Divinity",
			"Master of Economics",
			"Master of Education",
			"Master of Educational Technology",
			"Master of Engineering",
			"Master of Engineering Management",
			"Master of Enterprise",
			"Master of European Law",
			"Master of Finance",
			"Master of Financial Economics",
			"Master of Financial Engineering",
			"Master of Financial Mathematics",
			"Master of Fine Arts",
			"Master of Health Administration",
			"Master of Health Science",
			"Master of Humanities",
			"Master of Industrial and Labor Relations",
			"Master of International Affairs",
			"Master of International Business",
			"Masters in International Economics",
			"Master of International Public Policy",
			"Master of International Studies",
			"Master of Information",
			"Master of Information Management",
			"Master of Information System Management",
			"Master of Islamic Studies",
			"Master of IT",
			"Master of Jurisprudence",
			"Master of Laws",
			"Master of Studies in Law",
			"Master of Landscape Architecture",
			"Master of Letters",
			"Master of Liberal Arts",
			"Master of Library and Information Science",
			"Master of Management",
			"Master of Mass Communication and Journalism",
			"Master of Mathematical Finance",
			"Master of Mathematics",
			"Master of Mathematics and Computer Science",
			"Master of Mathematics and Philosophy",
			"Master of Medical Science",
			"Master of Medicine",
			"Masters of Military Art and Science",
			"Master of Music",
			"Master of Network and Communications Management",
			"Master of Occupational Therapy",
			"Master of Pharmacy",
			"Master of Philosophy",
			"Master of Physician Assistant Studies",
			"Master of Physics",
			"Master of Political Science",
			"Master of Professional Studies",
			"Master of Public Administration",
			"Master of Public Affairs",
			"Master of Public Diplomacy",
			"Master of Public Health",
			"Master of Public Management",
			"Master of Public Policy",
			"Master of Public Relations",
			"Master of Public Service",
			"Master of Quantitative Finance",
			"Master of Rabbinic Studies",
			"Master of Real Estate Development",
			"Master of Religious Education",
			"Master of Research",
			"Master of Sacred Music",
			"Master of Sacred Theology",
			"MSc Applied Cognition and Neuroscience",
			"MSc Bioinformatics",
			"MSc Clinical Epidemiology",
			"MSc Computing Research",
			"MSc Cyber Security",
			"MSc Education",
			"MSc Engineering",
			"MSc Development Administration",
			"MSc Finance",
			"MSc Governance & Organizational Sciences",
			"MSc Government Contracts",
			"MSc Health Informatics",
			"MSc Human Resource Development",
			"MSc Information Assurance",
			"MSc Information Systems",
			"MSc Information Technology",
			"MSc Leadership",
			"MSc Management",
			"MSc Nursing",
			"MSc Project Management",
			"MSc Quality Assurance",
			"MSc Risk Management",
			"MSc Supply Chain Management",
			"MSc Teaching",
			"MSc Taxation",
			"Master of Social Science",
			"Master of Social Work",
			"Master of Statistics",
			"Master of Studies",
			"Master of Surgery",
			"Master of Theological Studies",
			"Master of Technology",
			"Master of Theology",
			"Master of Urban Planning",
			"Master of Veterinary Science"
    ];
 
  $("#input-name-of-master-courses").autocomplete({
      source: availableMasterCourses,
      minLength: 3
  });
});