// Code goes here

$(function() {
    
    var availableUniversities = [
      "The University of Aberdeen",
      "University of Abertay Dundee",
      "Aberystwyth University",
      "ALRA (The Academy of Live and Recorded Arts)",
      "Accrington & Rossendale College",
      "The College of Agriculture, Food and Rural Enterprise",
      "American InterContinental University - London",
      "Anglia Ruskin University",
      "Anglo European College of Chiropractic",
      "Askham Bryan College",
      "Aston University",
      "Bangor University",
      "Barking and Dagenham College",
      "Barony College",
      "Basingstoke College of Technology",
      "University of Bath",
      "Bath Spa University",
      "City of Bath College",
      "University of Bedfordshire",
      "Bedford College",
      "Birkbeck College, University of London",
      "Birmingham City University",
      "Birmingham Metropolitan College",
      "University of Birmingham",
      "University College Birmingham",
      "Bishop Burton College",
      "Bishop Grosseteste University College Lincoln",
      "Blackburn College",
      "Blackpool and The Fylde College (An Associate College of Lancaster University)",
      "University of Bolton",
      "Bournemouth University",
      "The Arts University College at Bournemouth (Formerly Arts Institute at Bournemouth)",
      "BPP University College Of Professional Studies",
      "University of Bradford",
      "Bradford College: An Associate College of Leeds Metropolitan University",
      "Bridgwater College",
      "University of Brighton",
      "Brighton and Sussex Medical School",
      "City of Bristol College",
      "University of Bristol",
      "Bristol Filton College",
      "University of the West of England, Bristol",
      "British College of Osteopathic Medicine",
      "Brooklands College",
      "Brunel University",
      "British School of Osteopathy",
      "University of Buckingham",
      "Buckinghamshire New University",
      "University of Cambridge",
      "Canterbury Christ Church University",
      "Capel Manor College, Enfield, Middlesex",
      "Cardiff University",
      "University of Wales Institute, Cardiff",
      "Castle College Nottingham",
      "Coleg Sir Gar / Carmarthenshire College",
      "University of Central Lancashire",
      "Central School of Speech and Drama, University of London",
      "University of Chester",
      "Chesterfield College",
      "Chichester College",
      "University of Chichester",
      "City University",
      "City College Coventry",
      "City College, Birmingham",
      "City of Sunderland College",
      "Cleveland College of Art and Design",
      "Cliff College",
      "Colchester Institute",
      "College of West Anglia",
      "Courtauld Institute of Art (University of London)",
      "Coventry University",
      "Cornwall College",
      "Craven College",
      "University for the Creative Arts",
      "University of Cumbria",
      "Croydon College",
      "De Montfort University",
      "University of Derby",
      "Dearne Valley College",
      "Doncaster College",
      "Duchy College",
      "Dudley College of Technology",
      "University of Dundee",
      "Durham University",
      "Ealing, Hammersmith and West London College",
      "University of East Anglia",
      "East End Computing and Business College",
      "University of East London",
      "East Riding College",
      "Easton College",
      "East Surrey College (incorporating Reigate School of Art, Design and Media)",
      "Edge Hill University",
      "The University of Edinburgh",
      "Edinburgh Napier University",
      "University of Essex",
      "European Business School, London",
      "European School of Economics",
      "European School of Osteopathy",
      "Exeter College",
      "University of Exeter",
      "University College Falmouth Incorporating Dartington College of Arts",
      "Farnborough College of Technology",
      "University of Glamorgan, Cardiff and Pontypridd",
      "University of Glasgow",
      "Glasgow Caledonian University",
      "Glasgow School of Art",
      "Gloucestershire College",
      "University of Gloucestershire",
      "Glyndwr University",
      "Goldsmiths, University of London",
      "Gower College Swansea",
      "University of Greenwich",
      "Greenwich School of Management",
      "Grimsby Institute of Further and Higher Education",
      "Guildford College of Further and Higher Education",
      "Harper Adams University College",
      "Havering College of Further and Higher Education",
      "Hereford College of Arts",
      "Heriot-Watt University, Edinburgh",
      "University of Hertfordshire",
      "Highbury College",
      "Heythrop College (University of London)",
      "UHI Millennium Institute (University of the Highlands and Islands)",
      "Holborn College",
      "Hopwood Hall College",
      "University of Huddersfield",
      "University of Hull",
      "Hull College",
      "Hull York Medical School",
      "Imperial College London",
      "Islamic College for Advanced Studies",
      "Keele University",
      "Kensington College of Business",
      "The University of Kent",
      "King's College London (University of London)",
      "Kingston University",
      "Kirklees College",
      "Lakes College - West Cumbria",
      "Lancaster University",
      "Leeds City College",
      "University of Leeds",
      "Leeds Trinity University College",
      "Leeds Metropolitan University",
      "Leeds College of Art",
      "Leeds College of Music",
      "University of Leicester",
      "Leicester College",
      "University of Lincoln",
      "University of Liverpool",
      "Lincoln College",
      "Liverpool Community College",
      "Liverpool Hope University",
      "Liverpool Institute for Performing Arts",
      "Liverpool John Moores University",
      "Coleg Llandrillo Cymru",
      "London College, UCK",
      "London Electronics College",
      "London Metropolitan University",
      "London School of Commerce",
      "London School of Science and Technology",
      "London School of Economics and Political Science (University of London)",
      "London South Bank University",
      "Loughborough College",
      "Loughborough University",
      "Manchester College",
      "University of Manchester",
      "Manchester Metropolitan University",
      "Medway School of Pharmacy",
      "Coleg Menai",
      "Mid-Cheshire College",
      "Middlesex University",
      "Moulton College",
      "Mountview Academy of Theatre Arts",
      "Myerscough College",
      "Nazarene Theological College",
      "Neath Port Talbot College",
      "Newcastle University",
      "New College Durham",
      "New College Nottingham",
      "New College Stamford",
      "New College Telford",
      "Newcastle College",
      "Newman University College, Birmingham",
      "University of Wales, Newport",
      "University of Northampton",
      "Norwich University College Of The Arts",
      "Newham College of Further Education",
      "NESCOT, Surrey",
      "North Devon College",
      "North East Worcestershire College",
      "North Glasgow College",
      "North Lindsey College",
      "Northumbria University",
      "North Warwickshire and Hinckley College",
      "Northbrook College Sussex",
      "City College Norwich",
      "University of Nottingham",
      "Nottingham Trent University",
      "Northumberland College",
      "Oxford University",
      "Oxford Brookes University",
      "University of London Institute in Paris",
      "Pembrokeshire College",
      "Oxford & Cherwell Valley College",
      "University Centre Peterborough",
      "University of Plymouth",
      "UCP Marjon - University College Plymouth St Mark & St John",
      "Peninsula College of Medicine & Dentistry",
      "University of Portsmouth",
      "Queen Margaret University, Edinburgh",
      "Queen Mary, University of London",
      "Queen's University Belfast",
      "Plymouth College of Art",
      "The University of Reading",
      "Regents Business School London",
      "Richmond, The American International University in London",
      "Robert Gordon University",
      "Roehampton University",
      "Ravensbourne College of Design and Communication",
      "Rose Bruford College",
      "Rotherham College of Arts and Technology",
      "Royal Academy of Dance",
      "Royal Holloway, University of London",
      "Royal Veterinary College (University of London)",
      "Royal Welsh College of Music and Drama (Coleg Brenhinol Cerdd a Drama Cymru)",
      "Royal Agricultural College",
      "Scottish Agricultural College",
      "University of Salford",
      "SAE Institute",
      "Sandwell College",
      "School of Oriental and African Studies (University of London)",
      "School of Pharmacy (University of London)",
      "University of Sheffield",
      "Sheffield Hallam University",
      "Ruskin College Oxford",
      "Shrewsbury College of Arts and Technology",
      "Sheffield College",
      "University of Southampton",
      "Solihull College",
      "Southampton Solent University",
      "Somerset College of Arts and Technology",
      "South Cheshire College",
      "South Devon College",
      "University of St Andrews",
      "Southwark College",
      "South Downs College",
      "South Nottingham College",
      "South East Essex College (Partner of the University of Essex)",
      "Southport College",
      "St George's, University of London",
      "St Helens College",
      "South Tyneside College",
      "St Mary's University College, Twickenham",
      "Sparsholt College Hampshire",
      "Staffordshire University",
      "Staffordshire University Regional Federation",
      "Stephenson College Coalville",
      "University of Stirling",
      "Stockport College",
      "Stourbridge College",
      "University of Strathclyde",
      "Stranmillis University College: A College of Queen's University Belfast",
      "University Campus Suffolk",
      "University of Sunderland",
      "University of Surrey",
      "University of Sussex",
      "Swansea University",
      "Swansea Metropolitan University",
      "Stratford upon Avon College",
      "Swindon College",
      "Teesside University",
      "Thames Valley University",
      "The University of Wales Trinity Saint David",
      "Tameside College",
      "Truro and Penwith College",
      "University of Ulster",
      "University of the West of Scotland",
      "University of the Arts London",
      "University College London (University of London)",
      "Uxbridge College",
      "Tyne Metropolitan College",
      "Wakefield College",
      "Warrington Collegiate",
      "University of Warwick",
      "Walsall College",
      "Warwickshire College",
      "West Cheshire College",
      "West Herts College, Watford Associate College of University of Hertfordshire",
      "University of Westminster",
      "Westminster Kingsway College",
      "West Thames College",
      "Wigan and Leigh College",
      "Wirral Metropolitan College",
      "Wiltshire College",
      "University of Wolverhampton",
      "University of Winchester",
      "University of Worcester",
      "Worcester College of Technology",
      "Writtle College",
      "University of York",
      "York College",
      "York St John University",
      "Yorkshire Coast College of Further and Higher Education"
    ];
 
  $("#input-name-of-universities").autocomplete({
      source: availableUniversities,
      minLength: 3
  });
});